// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {folderselector} from '../models';
import {config} from '../models';
import {time} from '../models';

export function FolderSelectorControl(arg1:string,arg2:folderselector.FolderSelectorCommand,arg3:string):Promise<folderselector.FolderSelectorResult>;

export function GetConfigValueString(arg1:config.ConfigItem):Promise<string>;

export function GetConfigValueStringList(arg1:config.ConfigItem):Promise<Array<string>>;

export function GetLocalIP():Promise<string>;

export function GetPeerList():Promise<Array<string>>;

export function GetSharedDirectory():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RunSynkOnPeer(arg1:string,arg2:Record<string, time.Time>):Promise<void>;

export function SetConfigItemStringList(arg1:config.ConfigItem,arg2:Array<string>):Promise<void>;

export function TestLANDiscovery():Promise<void>;
