// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FolderSelectorControl(arg1, arg2, arg3) {
  return window['go']['main']['App']['FolderSelectorControl'](arg1, arg2, arg3);
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetPeerList() {
  return window['go']['main']['App']['GetPeerList']();
}

export function GetSharedDirectory() {
  return window['go']['main']['App']['GetSharedDirectory']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RunSynkOnPeer(arg1, arg2) {
  return window['go']['main']['App']['RunSynkOnPeer'](arg1, arg2);
}

export function TestLANDiscovery() {
  return window['go']['main']['App']['TestLANDiscovery']();
}
