// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {folderselector} from '../models';

export function FolderSelectorControl(arg1:string,arg2:folderselector.FolderSelectorCommand,arg3:string):Promise<folderselector.FolderSelectorResult>;

export function Greet(arg1:string):Promise<string>;

export function RunSynk():Promise<void>;

export function SetSharedDirectory(arg1:string):Promise<void>;
