// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FolderSelectorControl(arg1, arg2, arg3) {
  return window['go']['main']['App']['FolderSelectorControl'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RunSynk() {
  return window['go']['main']['App']['RunSynk']();
}

export function SetSharedDirectory(arg1) {
  return window['go']['main']['App']['SetSharedDirectory'](arg1);
}
